### ISSUE TITLE
[Server/Error] Could not load this mod correctly in 1.18.2 Server,forge version 40.2.9,mod version 5.1.5.

### ISSUE THREAD

**Issue by Jasmine1919810** [Reforged-Mods/Traverse-Reforged#4]
Failed to handle CraftCrashReport:
java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getName()" because "org.bukkit.Bukkit.server" is null
        at TRANSFORMER/forge@40.2.9/org.bukkit.Bukkit.getName(Bukkit.java:102)
        at TRANSFORMER/forge@40.2.9/org.bukkit.craftbukkit.v1_18_R2.CraftCrashReport.get(CraftCrashReport.java:23)
        at TRANSFORMER/forge@40.2.9/org.bukkit.craftbukkit.v1_18_R2.CraftCrashReport.get(CraftCrashReport.java:17)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.m_143522_(SystemReport.java:65)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.<init>(CrashReport.java:34)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.m_127521_(CrashReport.java:206)
        at TRANSFORMER/forge@40.2.9/net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55)
        at TRANSFORMER/forge@40.2.9/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Main.main(Main.java:142)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.9/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at com.mohistmc.util.BootstrapLauncher.startServer(BootstrapLauncher.java:100)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:90)

        ModLauncher: 9.1.3+9.1.3+main.9b69c82a
        ModLauncher launch target: forgeserver
        ModLauncher naming: srg
        ModLauncher services:
                 mixin PLUGINSERVICE
                 eventbus PLUGINSERVICE
                 slf4jfixer PLUGINSERVICE
                 object_holder_definalize PLUGINSERVICE
                 runtime_enum_extender PLUGINSERVICE
                 capability_token_subclass PLUGINSERVICE
                 accesstransformer PLUGINSERVICE
                 runtimedistcleaner PLUGINSERVICE
                 mixin TRANSFORMATIONSERVICE
                 fml TRANSFORMATIONSERVICE
        FML Language Providers:
                minecraft@1.0
                lowcodefml@null
                javafml@null
        Mod List:
                server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
                [TerraBlender]TerraBlender-forge-1.18.2-1.2.0.126.|TerraBlender                  |terrablender                  |1.2.0.126           |COMMON_SET|Manifest: NOSIGNATURE
                forge-1.18.2-40.2.9-universal.jar                 |Forge                         |forge                         |40.2.9              |COMMON_SET|Manifest: NOSIGNATURE
                terraform-tree-api-v1-3.1.5.jar                   |Terraform Tree API (v1) Reforg|terraform_tree_api_v1         |3.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                **traverse-client-5.1.5.jar                         |Traverse Reforged: client     |traverse_client               |5.1.5               |ERROR**     |Manifest: NOSIGNATURE
                terraform-dirt-api-v1-3.1.5.jar                   |Terraform Dirt API (v1) Reforg|terraform_dirt_api_v1         |3.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                terraform-utils-v1-3.1.5.jar                      |Terraform Utils               |terraform_utils               |3.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                [Fabric's Biome API Reforged]FabricBiomeApiReforge|Fabric BiomeApi Reforged      |fabric_biome_api              |2.0.3               |COMMON_SET|Manifest: NOSIGNATURE
                [Traverse Reforged]traverse-forge-5.1.5.jar       |Traverse Reforged             |traverse                      |5.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                terraform-config-api-v1-3.1.4.jar                 |Terraform Config API (v1) Refo|terraform_config_api_v1       |3.1.4               |COMMON_SET|Manifest: NOSIGNATURE
                terraform-wood-api-v1-3.1.5.jar                   |Terraform Wood API (v1) Reforg|terraform_wood_api_v1         |3.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                traverse-common-5.1.5.jar                         |Traverse Reforged: Common     |traverse_common               |5.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                traverse-worldgen-5.1.5.jar                       |Traverse Reforged: World Gener|traverse_worldgen             |5.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                [Terraformed Api Reforged]terraform-forge-3.1.5.ja|Terraform Api Reforged        |terraform                     |3.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                terraform-shapes-api-v1-3.1.5.jar                 |Terraform Shapes API (v1) Refo|terraform_shapes_api_v1       |3.1.5               |COMMON_SET|Manifest: NOSIGNATURE
                terraform-surfaces-api-v1-3.1.4.jar               |Terraform Surfaces API (v1) Re|terraform_surfaces_api_v1     |3.1.4               |COMMON_SET|Manifest: NOSIGNATURE
        Crash Report UUID: 19e2d9ea-09fa-4e5b-b6fe-0954351c6cdb
        FML: 38.0
        Forge: net.minecraftforge:40.2.9[09:23:15 ERROR]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        **Traverse Reforged: client (traverse_client) has failed to load correctly**
§7java.lang.reflect.InvocationTargetException: null
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:221) ~[fmlcore-1.18.2-40.2.9.jar%2363!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:186) ~[fmlcore-1.18.2-40.2.9.jar%2363!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186) ~[fmlcore-1.18.2-40.2.9.jar%2363!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:163) ~[fmlcore-1.18.2-40.2.9.jar%2363!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:163) ~[fmlcore-1.18.2-40.2.9.jar%2363!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.2.9-universal.jar%2367!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:142) ~[server-1.18.2-20220404.173914-srg.jar%2362!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.9.jar%2334!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at com.mohistmc.util.BootstrapLauncher.startServer(BootstrapLauncher.java:100) [mohist-1.18.2-31-server.jar:?] {}
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:90) [mohist-1.18.2-31-server.jar:1.18.2-31] {}

**Comment by GaoXanSheng** [comment]
According to the commits issue, the latest version number that has been fixed is 5.1.5.1. You can try cloning the source code to build the latest file

**Comment by Trinsdar** [comment]
fixed
